prefixes:
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  owl: http://www.w3.org/2002/07/owl#
  dct: http://purl.org/dc/terms/
  dc: http://purl.org/dc/elements/1.1/
  skos: http://www.w3.org/2004/02/skos/core#
  chembl: http://rdf.ebi.ac.uk/terms/chembl#


sparql:
  #uri: http://sparql:8890/sparql
  #uri: http://ops2.few.vu.nl:3030/chembl19/sparql
  uri: http://ops2.few.vu.nl:8890/sparql
  timeout_s: 7200 # e.g. 2 hours


elasticsearch:
  host: localhost
  # host: elasticsearch

common_properties:
  - rdfs:label

indexes:
  chembl:
    substance:
        graph: http://rdf.ebi.ac.uk/terms/chembl
        type: chembl:Substance
        subclasses: owl
        properties:
          - dct:title
          - dc:title
          - rdfs:description
          - skos:prefLabel
          - skos:altLabel
    target:
        graph: http://rdf.ebi.ac.uk/terms/chembl
        type: chembl:Target
        subclasses: owl
        properties:
          - dct:title

    targetComponent:
        graph: http://rdf.ebi.ac.uk/terms/chembl
        type: chembl:TargetComponent
        properties:
          - dct:title
          - skos:altLabel
          - dct:description
          - chembl:organismName
