
elasticsearch:
  - host: localhost
    port: 9200

prefixes:
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  owl: http://www.w3.org/2002/07/owl#
  dct: http://purl.org/dc/terms/
  dc: http://purl.org/dc/elements/1.1/
  skos: http://www.w3.org/2004/02/skos/core#
  dbpedia: http://dbpedia.org/ontology/
  dbprop: http://dbpedia.org/proeprty/


sparql:
  uri: http://dbpedia.org/sparql
  timeout_s: 60 # 1 minute
  limit: 100 # for debugging we don't want to index everything :-)

common_properties:
  - rdfs:label
  - rdfs:comment

indexes:
  dbpedia:
    person:
        type: foaf:Person
        properties:
          - foaf:givenName
          - foaf:surname
          - dc:description
          - dbprop:shortDescription
          - dbprop:dateOfBirth
          - dbpedia:abstract
    athlete:
        graph: http://www.openlinksw.com/schemas/virtrdf#
        type: dbpedia:Athlete
        subclasses: owl
        properties:
          - dbprop:alternativeNames
          - dbprop:fullname
          - dbprop:goals
          - dbpedia:abstract

